/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Dao.KhachHangDao;
import Dao.LoaiNguyenLieuDao;
import Dao.NguyenLieuDao;
import Dao.TaiKhoanDao;
import static GUI.FormKhachHang.model;
import Model.KhachHang;
import Model.NguyenLieu;
import Model.NhanVien;
import ServerController.Server;
import Utils.DateHelper;
import Utils.TimeHelper;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PhamNgocMinh
 */
public class TrangQuanLy extends javax.swing.JFrame implements Runnable{

    CardLayout CardLayout;
    public NhanVien nv = new NhanVien();


    public TrangQuanLy() {
        initComponents();
        CardLayout = (CardLayout) jPanel2.getLayout();

        this.setExtendedState(TrangQuanLy.MAXIMIZED_HORIZ);
        setLocationRelativeTo(null);
        CardLayout.show(jPanel2, "cardNhanVien");
        //  LoadData(); 
        TimeHelper.showClock(lblClock1);
        DateHelper.showClock(lblDate);
    }
    public void setnv(NhanVien nv){
        this.nv = nv;
        txttenuser.setText("Quản lý "+ nv.getTen());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void LoadData() {
        ArrayList<KhachHang> ds = new KhachHangDao().GetArrayListAll();
        model.setColumnIdentifiers(new Object[]{"Mã Khách Hàng", "Tên Khách hàng", "SDT", "Ngày Tạo", "LastActive", "Mã Người Tạo"});
        model.setRowCount(0);
        for (int i = 0; i < ds.size(); i++) {
            model.addRow(new Object[]{
                ds.get(i).getMaKH(),
                ds.get(i).getTenKH(),
                ds.get(i).getNgayTao(),
                ds.get(i).getLastActive(),
                ds.get(i).getMaNguoiTao()
            });
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDaodien = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSanPham = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        btnKhachHang = new javax.swing.JToggleButton();
        btnNhaCungCap = new javax.swing.JToggleButton();
        btnBanHang = new javax.swing.JToggleButton();
        btnHoaDon = new javax.swing.JToggleButton();
        btnPhanHoi = new javax.swing.JToggleButton();
        btnPhanHoi1 = new javax.swing.JToggleButton();
        btnPhanHoi2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPhanHoi3 = new javax.swing.JToggleButton();
        btnDangxuat = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        formNhanVien1 = new GUI.FormNhanVien();
        formNhaCungCap2 = new GUI.FormNhaCungCap();
        formHoadon1 = new GUI.FormHoadon();
        formQuanLyTaiKhoan1 = new GUI.FormQuanLyTaiKhoan();
        formSanPham1 = new GUI.FormSanPham();
        datMonJPanel1 = new GUI.datMonJPanel();
        thongKePanel2 = new GUI.ThongKePanel();
        nhapHangJpanel1 = new GUI.NhapHangJpanel();
        formKhachHang1 = new GUI.FormKhachHang();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblClock1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttenuser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btgDaodien.add(btnSanPham);
        btnSanPham.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/products.png"))); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        jToggleButton2.setText("jToggleButton1");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        btgDaodien.add(btnKhachHang);
        btnKhachHang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rating.png"))); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btgDaodien.add(btnNhaCungCap);
        btnNhaCungCap.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/supplier.png"))); // NOI18N
        btnNhaCungCap.setText("Nhà Cung Cấp");
        btnNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCapActionPerformed(evt);
            }
        });

        btgDaodien.add(btnBanHang);
        btnBanHang.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/coupon.png"))); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btgDaodien.add(btnHoaDon);
        btnHoaDon.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bill.png"))); // NOI18N
        btnHoaDon.setText("Hoá Đơn");
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btgDaodien.add(btnPhanHoi);
        btnPhanHoi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnPhanHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user (1).png"))); // NOI18N
        btnPhanHoi.setText("Nhập Kho");
        btnPhanHoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhanHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanHoiActionPerformed(evt);
            }
        });

        btgDaodien.add(btnPhanHoi1);
        btnPhanHoi1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnPhanHoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff.png"))); // NOI18N
        btnPhanHoi1.setText("Nhân Viên");
        btnPhanHoi1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhanHoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanHoi1ActionPerformed(evt);
            }
        });

        btgDaodien.add(btnPhanHoi2);
        btnPhanHoi2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnPhanHoi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/chat.png"))); // NOI18N
        btnPhanHoi2.setText("Phản Hồi");
        btnPhanHoi2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhanHoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanHoi2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        jLabel1.setText("Quản Lý");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/TM.png"))); // NOI18N

        btgDaodien.add(btnPhanHoi3);
        btnPhanHoi3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnPhanHoi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user (1).png"))); // NOI18N
        btnPhanHoi3.setText("Tài Khoản");
        btnPhanHoi3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhanHoi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanHoi3ActionPerformed(evt);
            }
        });

        btgDaodien.add(btnDangxuat);
        btnDangxuat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnDangxuat.setText("Thống kê");
        btnDangxuat.setToolTipText("");
        btnDangxuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
            .addComponent(btnNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPhanHoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPhanHoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPhanHoi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPhanHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(btnDangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnPhanHoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnPhanHoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhanHoi3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhanHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnDangxuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(547, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBanHang, btnDangxuat, btnHoaDon, btnKhachHang, btnNhaCungCap, btnPhanHoi, btnPhanHoi1, btnPhanHoi2, btnPhanHoi3, btnSanPham});

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(formNhanVien1, "cardNhanVien");
        jPanel2.add(formNhaCungCap2, "cardNhaCungCap");
        jPanel2.add(formHoadon1, "card5");
        jPanel2.add(formQuanLyTaiKhoan1, "card6");
        jPanel2.add(formSanPham1, "card7");
        jPanel2.add(datMonJPanel1, "datmoncard");
        jPanel2.add(thongKePanel2, "thongkePanel");
        jPanel2.add(nhapHangJpanel1, "NhapHangCard");
        jPanel2.add(formKhachHang1, "cardKhachHang");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ngày :");

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("12:23:23");
        lblDate.setToolTipText("");
        lblDate.setName(""); // NOI18N

        lblClock1.setBackground(new java.awt.Color(255, 255, 255));
        lblClock1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblClock1.setForeground(new java.awt.Color(255, 255, 255));
        lblClock1.setText("12:23:23");
        lblClock1.setToolTipText("");
        lblClock1.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Giờ : ");

        txttenuser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txttenuser.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttenuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDate)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClock1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClock1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttenuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Thông tin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("Nguyên liệu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        CardLayout.show(jPanel2, "card7");
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        CardLayout.show(jPanel2, "cardKhachHang");
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCapActionPerformed
        CardLayout.show(jPanel2, "cardNhaCungCap");
    }//GEN-LAST:event_btnNhaCungCapActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        CardLayout.show(jPanel2,"datmoncard");
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        CardLayout.show(jPanel2, "card5");
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnPhanHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanHoiActionPerformed
        CardLayout.show(jPanel2, "NhapHangCard");
    }//GEN-LAST:event_btnPhanHoiActionPerformed

    private void btnPhanHoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanHoi1ActionPerformed
        CardLayout.show(jPanel2, "cardNhanVien");
    }//GEN-LAST:event_btnPhanHoi1ActionPerformed

    private void btnPhanHoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanHoi2ActionPerformed
        JOptionPane.showMessageDialog(this, "Đang trong quá trình thử nghiệm!!");
    }//GEN-LAST:event_btnPhanHoi2ActionPerformed

    private void btnPhanHoi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanHoi3ActionPerformed
        CardLayout.show(jPanel2, "card6");
    }//GEN-LAST:event_btnPhanHoi3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
        FormDangNhap fdn = new FormDangNhap();
        JOptionPane.showMessageDialog(null, "Mời Đăng Nhập Lại");
        fdn.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        CardLayout.show(jPanel2, "thongkePanel");
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormThongTinNguoiDung forminfo = new FormThongTinNguoiDung();
        forminfo.setAlwaysOnTop(true);
        forminfo.setForm(Server.testGui.nv);
        forminfo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
//        ID");
//                String ten = rs.getString("TEN");
//                BigDecimal dongia = rs.getBigDecimal("Dongia");
//                Date ngayTao = rs.getDate("NgayTao");
//                Date ngayKetThuc = rs.getDate("NgayKetThuc");
//                int soluong = rs.getInt("soluong");
//                String dvt = rs.getString("DVT");
//                String idLoai = rs.getString("IDLoai");
        JFrame nljf = new JFrame();
        nljf.setPreferredSize(new Dimension(500, 300));
        nljf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        JTable jt = new JTable();
        ArrayList<NguyenLieu> dsnl = new NguyenLieuDao().GetArrayListAll();
        DefaultTableModel modelnl= new DefaultTableModel();
        modelnl = (DefaultTableModel) jt.getModel();
        
        modelnl.setColumnIdentifiers(new Object[]{"ID", "Tên", "Đơn giá", "Ngày Tạo","Số lượng","Đơn vị", "NgayKetThuc", "Loại"});
        modelnl.setRowCount(0);
        for (NguyenLieu nl: dsnl) {
            modelnl.addRow(new Object[]{
                nl.getId(),
                nl.getTen(),
                nl.getDongia().toString(),
                nl.getNgayTao(),
                nl.getSoluong(),
                nl.getDvt(),
                nl.getNgayKetThuc()==null?"":nl.getNgayKetThuc(),
                new LoaiNguyenLieuDao().getObjectById(nl.getIdLoai()).getTen()
            });
        }
        JPanel jp = new JPanel();
        jp.setPreferredSize(new Dimension(500, 300));
        jp.setLayout(new FlowLayout());
        jp.add(jt);
        nljf.add(jp);
        nljf.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDaodien;
    private javax.swing.JToggleButton btnBanHang;
    private javax.swing.JToggleButton btnDangxuat;
    private javax.swing.JToggleButton btnHoaDon;
    private javax.swing.JToggleButton btnKhachHang;
    private javax.swing.JToggleButton btnNhaCungCap;
    private javax.swing.JToggleButton btnPhanHoi;
    private javax.swing.JToggleButton btnPhanHoi1;
    private javax.swing.JToggleButton btnPhanHoi2;
    private javax.swing.JToggleButton btnPhanHoi3;
    private javax.swing.JToggleButton btnSanPham;
    private javax.swing.ButtonGroup buttonGroup1;
    public GUI.datMonJPanel datMonJPanel1;
    private GUI.FormHoadon formHoadon1;
    private GUI.FormKhachHang formKhachHang1;
    private GUI.FormNhaCungCap formNhaCungCap2;
    private GUI.FormNhanVien formNhanVien1;
    private GUI.FormQuanLyTaiKhoan formQuanLyTaiKhoan1;
    public GUI.FormSanPham formSanPham1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblClock1;
    private javax.swing.JLabel lblDate;
    private GUI.NhapHangJpanel nhapHangJpanel1;
    public GUI.ThongKePanel thongKePanel2;
    private javax.swing.JLabel txttenuser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        this.setVisible(true);
    }
}
